"""Add premium fields to user

Revision ID: f91c91cb4b4c
Revises: 6637ba5b0bf7
Create Date: 2026-07-06 16:34:35.662710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f91c91cb4b4c'
down_revision: Union[str, Sequence[str], None] = '6637ba5b0bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    op.alter_column('applications', 'cover_letter',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'SHORTLISTED', 'REJECTED', 'ACCEPTED', name='applicationstatus'),
               existing_nullable=False)
    op.alter_column('internships', 'recruiter_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('premium_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('free_chat_used', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('free_resume_used', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_resume_used')
    op.drop_column('users', 'free_chat_used')
    op.drop_column('users', 'premium_expiry')
    op.alter_column('internships', 'recruiter_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('PENDING', 'SHORTLISTED', 'REJECTED', 'ACCEPTED', name='applicationstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('applications', 'cover_letter',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('resumes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('resumes_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey')),
    sa.UniqueConstraint('student_id', name=op.f('resumes_student_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
